<a href="https://colab.research.google.com/github/sumanth-dp/Pytorch/blob/main/ANN_with_nnModule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import torch.nn as nn

In [7]:
class ANN(nn.Module):
  def __init__(self):

    super().__init__()

    self.layer1 = nn.Linear(5,8)

    self.relu1 = nn.ReLU()

    self.layer2 = nn.Linear(8, 5)

    self.relu2 = nn.ReLU()

    self.output_layer = nn.Linear(5,1)

    self.sigmoid = nn.Sigmoid()

  def forward(self, x):

    output1 = self.layer1(x)

    output2 = self.relu1(output1)

    output3 = self.layer2(output2)

    output4 = self.relu2(output3)

    output5 = self.output_layer(output4)

    output6 = self.sigmoid(output5)


    return output6

In [8]:
x=torch.randn(10,5)
print(x)
y=torch.rand(10,1)
print(y)

tensor([[ 0.2645,  0.6982, -1.3406, -2.9850, -0.4960],
        [ 1.3040,  0.3899,  0.0333, -0.0244,  0.8690],
        [-0.6465, -0.4993, -0.0827,  1.5046,  0.5485],
        [-1.2912, -0.7203,  0.1417,  0.4041, -0.5652],
        [ 0.6556, -1.3175,  1.6054, -0.2783, -2.5778],
        [ 1.2129, -0.7508,  0.1138,  0.9923, -0.1229],
        [-0.9861, -1.3130, -0.7251,  1.7456,  1.6347],
        [ 1.3099,  0.4052,  0.8075,  0.6083,  0.9170],
        [ 1.6678, -2.4792, -1.1623, -0.1793, -1.3263],
        [ 0.9445,  0.0161, -0.6466,  0.1723, -1.1287]])
tensor([[0.7102],
        [0.2348],
        [0.7998],
        [0.8676],
        [0.8724],
        [0.3434],
        [0.2834],
        [0.1109],
        [0.8672],
        [0.4330]])


In [9]:
model = ANN()

y_pred = model(x)

y_pred

tensor([[0.4447],
        [0.4161],
        [0.4358],
        [0.4441],
        [0.3902],
        [0.4286],
        [0.4274],
        [0.4307],
        [0.4199],
        [0.4369]], grad_fn=<SigmoidBackward0>)

In [10]:
y_pred.shape

torch.Size([10, 1])