<a href="https://colab.research.google.com/github/sumanth-dp/Pytorch/blob/main/grad_for_differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x=torch.tensor(2.0,requires_grad=True)

In [ ]:
x

tensor(2., dtype=torch.float64, requires_grad=True)

In [ ]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
z=torch.sin(y)
z

tensor(-0.7568, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
x=torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z=torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

In [ ]:
# manual operation
x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [ ]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss=y*torch.log(y_pred)-(1-y)*torch.log(1-y_pred)
loss

tensor(6.7012, grad_fn=<SubBackward0>)

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
x=torch.tensor([1,2,3],dtype=torch.float64,requires_grad=True)
x

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)

In [ ]:
y=(x**2).mean()
y

tensor(4.6667, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000], dtype=torch.float64)

In [ ]:
x

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)

clearing grad

In [ ]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(12.)

In [ ]:
x.grad.zero_()

tensor(0.)

In [ ]:
# option 1- requires_grad_(False)
# option 2- detach()
# option 3- torch.no_grad()

In [ ]:
x.requires_grad_(False)

tensor(2.)

In [ ]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
z=x.detach
z

<function Tensor.detach>

In [ ]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
with torch.no_grad():
  y=x**2
y

tensor(4.)