In [2]:
import torch

In [3]:
print(torch.__version__)

2.11.0+cpu


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available using CPU.")

GPU is not available using CPU.


**Creating Tensors**

In [6]:
# using empty
torch.empty(2,3)

tensor([[ 1.6333e-38,  0.0000e+00, -2.4695e-08],
        [ 4.3918e-41, -1.4481e+29,  4.3918e-41]])

In [8]:
# using check type
a = torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [9]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using rand
torch.rand(2,3)

tensor([[0.3548, 0.0622, 0.2669],
        [0.6473, 0.9322, 0.5874]])

In [12]:
torch.rand(2,3)

tensor([[0.8753, 0.3419, 0.3360],
        [0.4880, 0.9982, 0.1287]])

In [13]:
# use manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

tensor

In [16]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [17]:
torch.tensor(torch.rand(2,3,4))

/tmp/ipykernel_3087/354688487.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(torch.rand(2,3,4))


tensor([[[0.2627, 0.0428, 0.2080, 0.1180],
         [0.1217, 0.7356, 0.7118, 0.7876],
         [0.4183, 0.9014, 0.9969, 0.7565]],

        [[0.2239, 0.3023, 0.1784, 0.8238],
         [0.5557, 0.9770, 0.4440, 0.9478],
         [0.7445, 0.4892, 0.2426, 0.7003]]])

In [20]:
# arrange
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#linspace
torch.linspace(1,20,6)

tensor([ 1.0000,  4.8000,  8.6000, 12.4000, 16.2000, 20.0000])

In [23]:
# eye, identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [27]:
# full
torch.full((4,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

tensor shapes


In [30]:
x= torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [31]:
x.shape

torch.Size([2, 3])

In [33]:
# empty_like initialize with size of x
torch.empty_like(x)

tensor([[             199757,                  36,                   0],
        [                  0,                   0, 7090129474773464373]])

In [34]:
# rand_like
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [44]:
y= torch.tensor([[1,2,3],[2,3,4]], dtype=torch.float32)
y

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [47]:
# rand_like
torch.rand_like(y)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [45]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [38]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

**Tensor Datatypes**

In [40]:
x.dtype

torch.int64

In [41]:
torch.tensor([2.0,3.6,5.7], dtype = torch.int32)

tensor([2, 3, 5], dtype=torch.int32)

In [43]:
torch.tensor([1,2,3], dtype= torch.float32)

tensor([1., 2., 3.])

In [49]:
# type conversion using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

**Mathematical operations**

scalar operations

In [51]:
x= torch.rand(2,2)
x

tensor([[0.5163, 0.0359],
        [0.6476, 0.3430]])

In [53]:
# addition
x.add(3)

tensor([[3.5163, 3.0359],
        [3.6476, 3.3430]])

In [54]:
# subtraction
x.sub(5)

tensor([[-4.4837, -4.9641],
        [-4.3524, -4.6570]])

In [55]:
# multiplication
x.mul(3)

tensor([[1.5488, 0.1077],
        [1.9429, 1.0291]])

In [56]:
# division
x.div(2)

tensor([[0.2581, 0.0179],
        [0.3238, 0.1715]])

In [58]:
x//2

tensor([[0., 0.],
        [0., 0.]])

In [59]:
x%3

tensor([[0.5163, 0.0359],
        [0.6476, 0.3430]])

In [60]:
x**7

tensor([[9.7757e-03, 7.6622e-11],
        [4.7786e-02, 5.5884e-04]])

element wise operation

In [61]:
a= torch.rand(2,3)
b= torch.rand(2,3)

In [62]:
a

tensor([[0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989]])

In [63]:
b

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])

In [64]:
a+b

tensor([[0.7632, 1.2539, 0.5009],
        [0.8512, 1.5262, 1.1519]])

In [65]:
a-b

tensor([[-0.1268, -0.2017, -0.4116],
        [ 0.1735,  0.2839,  0.0458]])

In [66]:
b-a

tensor([[ 0.1268,  0.2017,  0.4116],
        [-0.1735, -0.2839, -0.0458]])

In [67]:
a*b

tensor([[0.1416, 0.3829, 0.0204],
        [0.1736, 0.5622, 0.3312]])

In [68]:
a/b

tensor([[0.7151, 0.7228, 0.0979],
        [1.5119, 1.4571, 1.0829]])

In [69]:
a//b

tensor([[0., 0., 0.],
        [1., 1., 1.]])

In [70]:
a%b

tensor([[0.3182, 0.5261, 0.0447],
        [0.1735, 0.2839, 0.0458]])

In [71]:
a**b

tensor([[0.6008, 0.6266, 0.2421],
        [0.7972, 0.9399, 0.7531]])

In [72]:
c= torch.tensor([-1,2,-3,4,5,6,-7])
c

tensor([-1,  2, -3,  4,  5,  6, -7])

In [73]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4, 5, 6, 7])

In [74]:
# neg
torch.neg(c)

tensor([ 1, -2,  3, -4, -5, -6,  7])

In [79]:
d=torch.rand(6)
d

tensor([0.3379, 0.2170, 0.9454, 0.7116, 0.1157, 0.6574])

In [80]:
# round
torch.round(d)

tensor([0., 0., 1., 1., 0., 1.])

In [81]:
torch.ceil(d)

tensor([1., 1., 1., 1., 1., 1.])

In [82]:
torch.floor(d)

tensor([0., 0., 0., 0., 0., 0.])

In [83]:
torch.clamp(d, min=2, max=3)

tensor([2., 2., 2., 2., 2., 2.])

Reduction Operation

In [84]:
e= torch.randint(size=(2,3), low =0, high=10)
e

tensor([[8, 4, 7],
        [2, 3, 8]])

In [85]:
torch.sum(e)

tensor(32)

In [87]:
torch.min(e)

tensor(2)

In [89]:
torch.max(e)

tensor(8)

In [90]:
# 0-column
# 1-row
torch.sum(e, dim=0)

tensor([10,  7, 15])

In [91]:
torch.sum(e,dim=1)

tensor([19, 13])

In [92]:
torch.min(e,dim=0)

torch.return_types.min(
values=tensor([2, 3, 7]),
indices=tensor([1, 1, 0]))

In [93]:
torch.min(e,dim=1)

torch.return_types.min(
values=tensor([4, 2]),
indices=tensor([1, 0]))

In [94]:
torch.max(e,dim=0)

torch.return_types.max(
values=tensor([8, 4, 8]),
indices=tensor([0, 0, 1]))

In [95]:
torch.max(e,dim=1)

torch.return_types.max(
values=tensor([8, 8]),
indices=tensor([0, 2]))

In [96]:
torch.mean(e)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [101]:
f=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float64)
f

tensor([[3., 9., 4.],
        [6., 7., 4.]], dtype=torch.float64)

In [102]:
torch.mean(f)

tensor(5.5000, dtype=torch.float64)

In [103]:
torch.mean(f, dim=0)

tensor([4.5000, 8.0000, 4.0000], dtype=torch.float64)

In [104]:
torch.mean(f,dim=1)

tensor([5.3333, 5.6667], dtype=torch.float64)

In [105]:
torch.median(f)

tensor(4., dtype=torch.float64)

In [106]:
torch.median(f,dim=0)

torch.return_types.median(
values=tensor([3., 7., 4.], dtype=torch.float64),
indices=tensor([0, 1, 0]))

In [107]:
torch.median(f,dim=1)

torch.return_types.median(
values=tensor([4., 6.], dtype=torch.float64),
indices=tensor([2, 0]))

In [108]:
torch.prod(f)

tensor(18144., dtype=torch.float64)

In [109]:
torch.prod(f,dim=0)

tensor([18., 63., 16.], dtype=torch.float64)

In [110]:
torch.prod(f,dim=1)

tensor([108., 168.], dtype=torch.float64)

In [111]:
torch.std(f)

tensor(2.2583, dtype=torch.float64)

In [112]:
torch.std(f,dim=0)

tensor([2.1213, 1.4142, 0.0000], dtype=torch.float64)

In [113]:
torch.std(f,dim=1)

tensor([3.2146, 1.5275], dtype=torch.float64)

In [114]:
torch.var(f)

tensor(5.1000, dtype=torch.float64)

In [115]:
torch.var(f,dim=0)

tensor([4.5000, 2.0000, 0.0000], dtype=torch.float64)

In [118]:
torch.argmax(f)

tensor(1)

In [119]:
torch.argmin(f)

tensor(0)

In [120]:
torch.argmax(f,dim=0)

tensor([1, 0, 0])

matrix operations

In [121]:
g=torch.randint(size=(2,3),low =1,high=10)
h=torch.randint(size=(2,3),low =1,high=10)

In [123]:
g

tensor([[7, 7, 7],
        [9, 9, 1]])

In [124]:
h

tensor([[9, 7, 6],
        [5, 2, 1]])

In [125]:
g+h

tensor([[16, 14, 13],
        [14, 11,  2]])

In [126]:
torch.add(g,h)

tensor([[16, 14, 13],
        [14, 11,  2]])

In [127]:
g*h

tensor([[63, 49, 42],
        [45, 18,  1]])

In [128]:
torch.matmul(g,h)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [129]:
g=torch.randint(size=(2,3),low =1,high=10)
h=torch.randint(size=(3,2),low =1,high=10)

In [130]:
g

tensor([[8, 6, 7],
        [2, 1, 7]])

In [131]:
h

tensor([[4, 1],
        [2, 8],
        [2, 2]])

In [132]:
g*h

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [133]:
torch.matmul(g,h)

tensor([[58, 70],
        [24, 24]])

In [134]:
torch.dot(g,h)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [135]:
vector1 = torch.tensor([1,2,3,4])
vector2 = torch.tensor([2,3,4,5])

In [136]:
vector1

tensor([1, 2, 3, 4])

In [137]:
vector2

tensor([2, 3, 4, 5])

In [138]:
torch.dot(vector1, vector2)

tensor(40)

In [141]:
h

tensor([[4, 1],
        [2, 8],
        [2, 2]])

In [143]:
# transpose
torch.transpose(h,0,1)

tensor([[4, 2, 2],
        [1, 8, 2]])

In [144]:
# transpose
torch.transpose(h,1,0)

tensor([[4, 2, 2],
        [1, 8, 2]])

In [145]:
torch.det(h)

RuntimeError: linalg.det: A must be batches of square matrices, but they are 3 by 2 matrices

In [149]:
h=torch.randint(size=(3,3), low=1,high=10,dtype=torch.float64)

In [150]:
h

tensor([[6., 2., 3.],
        [4., 3., 2.],
        [9., 5., 1.]], dtype=torch.float64)

In [151]:
torch.det(h)

tensor(-35., dtype=torch.float64)

In [152]:
torch.inverse(h)

tensor([[ 2.0000e-01, -3.7143e-01,  1.4286e-01],
        [-4.0000e-01,  6.0000e-01, -3.1721e-17],
        [ 2.0000e-01,  3.4286e-01, -2.8571e-01]], dtype=torch.float64)

comparision operations

In [153]:
i = torch.randint(size=(2,3), low=1,high=10)
j=torch.randint(size=(2,3),low=1,high=10)

In [154]:
i

tensor([[6, 4, 3],
        [8, 1, 5]])

In [155]:
j

tensor([[4, 4, 9],
        [1, 9, 2]])

In [156]:
i>j

tensor([[ True, False, False],
        [ True, False,  True]])

In [157]:
i<j

tensor([[False, False,  True],
        [False,  True, False]])

In [158]:
i==j

tensor([[False,  True, False],
        [False, False, False]])

In [159]:
i!=j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [160]:
i<=j

tensor([[False,  True,  True],
        [False,  True, False]])

In [161]:
i>=j

tensor([[ True,  True, False],
        [ True, False,  True]])

special functions

In [172]:
k= torch.randint(size=(2,3),low=1, high=10)

In [163]:
k

tensor([[3, 3, 2],
        [4, 4, 6]])

In [164]:
torch.log(k)

tensor([[1.0986, 1.0986, 0.6931],
        [1.3863, 1.3863, 1.7918]])

In [165]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 1.4142],
        [2.0000, 2.0000, 2.4495]])

In [166]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.8808],
        [0.9820, 0.9820, 0.9975]])

In [173]:
# softmax
torch.softmax(k, dim=0)

NotImplementedError: "softmax_kernel_impl" not implemented for 'Long'

In [174]:
k=torch.tensor([1,2,3,4,5,6], dtype=torch.float64)
k

tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)

In [175]:
torch.softmax(k, dim=0)

tensor([0.0043, 0.0116, 0.0315, 0.0858, 0.2331, 0.6337], dtype=torch.float64)

In [176]:
torch.relu(k)

tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)

inplace operations

In [177]:
m=torch.randint(size=(2,3),low=1,high=10)
n=torch.randint(size=(2,3),low=1,high=10)

In [178]:
m

tensor([[4, 9, 4],
        [7, 8, 6]])

In [179]:
n


tensor([[4, 7, 1],
        [5, 2, 5]])

In [180]:
m+n

tensor([[ 8, 16,  5],
        [12, 10, 11]])

In [181]:
m

tensor([[4, 9, 4],
        [7, 8, 6]])

In [182]:
n

tensor([[4, 7, 1],
        [5, 2, 5]])

In [183]:
m.add(n)

tensor([[ 8, 16,  5],
        [12, 10, 11]])

In [184]:
m

tensor([[4, 9, 4],
        [7, 8, 6]])

In [185]:
m.add_(n)

tensor([[ 8, 16,  5],
        [12, 10, 11]])

In [186]:
m

tensor([[ 8, 16,  5],
        [12, 10, 11]])

In [187]:
n

tensor([[4, 7, 1],
        [5, 2, 5]])

In [188]:
m.sub_(n)

tensor([[4, 9, 4],
        [7, 8, 6]])

In [189]:
m.mul_(n)

tensor([[16, 63,  4],
        [35, 16, 30]])

In [190]:
m.div_(n)

RuntimeError: result type Float can't be cast to the desired output type Long

In [191]:
m.abs_()

tensor([[16, 63,  4],
        [35, 16, 30]])

In [192]:
m.relu_()

tensor([[16, 63,  4],
        [35, 16, 30]])

In [193]:
m.sigmoid_()

RuntimeError: result type Float can't be cast to the desired output type Long

copying a tensor

In [194]:
a= torch.rand(2,3)

In [195]:
a

tensor([[0.7555, 0.6458, 0.3673],
        [0.1770, 0.2966, 0.9925]])

In [196]:
a=b

In [197]:
a

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])

In [198]:
b

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])

In [199]:
a.add(2)

tensor([[2.4450, 2.7278, 2.4563],
        [2.3389, 2.6211, 2.5530]])

In [200]:
a

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])

In [201]:
b

tensor([[0.4450, 0.7278, 0.4563],
        [0.3389, 0.6211, 0.5530]])

In [202]:
a[0][0]=100

In [203]:
a

tensor([[100.0000,   0.7278,   0.4563],
        [  0.3389,   0.6211,   0.5530]])

In [204]:
b

tensor([[100.0000,   0.7278,   0.4563],
        [  0.3389,   0.6211,   0.5530]])

In [205]:
id(a)

134611559186592

In [206]:
id(b)

134611559186592

In [207]:
c=a.clone()

In [208]:
a

tensor([[100.0000,   0.7278,   0.4563],
        [  0.3389,   0.6211,   0.5530]])

In [209]:
c

tensor([[100.0000,   0.7278,   0.4563],
        [  0.3389,   0.6211,   0.5530]])

In [210]:
a[0][1]=400

In [211]:
a

tensor([[1.0000e+02, 4.0000e+02, 4.5626e-01],
        [3.3887e-01, 6.2115e-01, 5.5302e-01]])

In [212]:
c

tensor([[100.0000,   0.7278,   0.4563],
        [  0.3389,   0.6211,   0.5530]])

In [214]:
c[1][0]=900

In [215]:
c

tensor([[1.0000e+02, 7.2783e-01, 4.5626e-01],
        [9.0000e+02, 6.2115e-01, 5.5302e-01]])

In [216]:
a

tensor([[1.0000e+02, 4.0000e+02, 4.5626e-01],
        [3.3887e-01, 6.2115e-01, 5.5302e-01]])

In [217]:
id(a)

134611559186592

In [218]:
id(c)

134611202655168

**Tensor operations on GPU**

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
device=torch.device('cuda')

In [6]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.7870, 0.2507, 0.8095],
        [0.4501, 0.2558, 0.2204]], device='cuda:0')

In [7]:
# moving to existing tensor to GPU

a=torch.rand(2,3)

a

tensor([[0.4071, 0.0185, 0.3878],
        [0.7989, 0.8741, 0.2886]])

In [8]:
a.to(device)

tensor([[0.4071, 0.0185, 0.3878],
        [0.7989, 0.8741, 0.2886]], device='cuda:0')

In [9]:
a+5

tensor([[5.4071, 5.0185, 5.3878],
        [5.7989, 5.8741, 5.2886]])

In [5]:
b=torch.rand(10000,10000)

In [6]:
b.to(device)


tensor([[0.9364, 0.4692, 0.8745,  ..., 0.0520, 0.1600, 0.1522],
        [0.7690, 0.6459, 0.4382,  ..., 0.0741, 0.9744, 0.8786],
        [0.4229, 0.9001, 0.9443,  ..., 0.5502, 0.6754, 0.7044],
        ...,
        [0.7416, 0.8837, 0.1752,  ..., 0.9025, 0.8019, 0.9903],
        [0.3873, 0.5419, 0.3119,  ..., 0.7364, 0.1207, 0.2813],
        [0.9843, 0.6951, 0.8690,  ..., 0.5087, 0.3393, 0.1538]],
       device='cuda:0')

In [7]:
b.mul(b)

tensor([[0.8768, 0.2201, 0.7647,  ..., 0.0027, 0.0256, 0.0232],
        [0.5914, 0.4172, 0.1921,  ..., 0.0055, 0.9494, 0.7720],
        [0.1788, 0.8101, 0.8918,  ..., 0.3027, 0.4561, 0.4962],
        ...,
        [0.5500, 0.7809, 0.0307,  ..., 0.8146, 0.6431, 0.9807],
        [0.1500, 0.2937, 0.0973,  ..., 0.5423, 0.0146, 0.0791],
        [0.9688, 0.4832, 0.7552,  ..., 0.2588, 0.1151, 0.0237]])

reshaping tensors

In [8]:
a=torch.ones(4,4)

In [9]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [11]:
a.reshape(2,2)

RuntimeError: shape '[2, 2]' is invalid for input of size 16

In [12]:
a.reshape(8,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b=torch.rand(2,3,4)

In [15]:
b

tensor([[[0.5022, 0.3863, 0.0126, 0.4972],
         [0.8548, 0.3642, 0.7057, 0.0692],
         [0.3095, 0.8953, 0.4183, 0.2622]],

        [[0.6799, 0.7853, 0.1170, 0.8776],
         [0.4310, 0.2401, 0.4906, 0.9271],
         [0.2233, 0.5378, 0.9916, 0.5773]]])

In [16]:
b.permute(2,0,1)

tensor([[[0.5022, 0.8548, 0.3095],
         [0.6799, 0.4310, 0.2233]],

        [[0.3863, 0.3642, 0.8953],
         [0.7853, 0.2401, 0.5378]],

        [[0.0126, 0.7057, 0.4183],
         [0.1170, 0.4906, 0.9916]],

        [[0.4972, 0.0692, 0.2622],
         [0.8776, 0.9271, 0.5773]]])

In [17]:
b.permute(2,1,0)

tensor([[[0.5022, 0.6799],
         [0.8548, 0.4310],
         [0.3095, 0.2233]],

        [[0.3863, 0.7853],
         [0.3642, 0.2401],
         [0.8953, 0.5378]],

        [[0.0126, 0.1170],
         [0.7057, 0.4906],
         [0.4183, 0.9916]],

        [[0.4972, 0.8776],
         [0.0692, 0.9271],
         [0.2622, 0.5773]]])

In [18]:
c= torch.rand(226,226,3)

In [21]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [22]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [24]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [26]:
d= torch.rand(1,20)

In [27]:
d.squeeze(0).shape

torch.Size([20])

**Numpy to Pytorch**

In [30]:
import numpy as np

In [31]:
a= torch.tensor([1,2,3])

In [34]:
a

tensor([1, 2, 3])

In [32]:
b=a.numpy()

In [33]:
b

array([1, 2, 3])

In [35]:
c= np.array([1,2,3,4])

In [36]:
c

array([1, 2, 3, 4])

In [37]:
d=torch.from_numpy(c)

In [38]:
d

tensor([1, 2, 3, 4])