<a href="https://colab.research.google.com/github/sumanth-dp/Pytorch/blob/main/SimpleNN_manual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import torch

class SimpleNN():

    def __init__(self, x, y):
        self.w = torch.rand(x.shape[1], 1,dtype=torch.float64, requires_grad=True)
        self.b = torch.zeros(1, dtype= torch.float64, requires_grad=True)

    def forwardPass(self):
        z = torch.matmul(x,self.w) + self.b
        y_pred = torch.sigmoid(z)
        return y_pred
    # these are retuning nan value
    # def calculate_loss(self, y_pred):
    #     loss = -(self.y * torch.log(y_pred) +
    #              (1 - self.y) * torch.log(1 - y_pred))
    #     return loss.mean()

    def calculate_loss(self, y,y_pred):
      y_pred = torch.clamp(y_pred, 1e-7, 1 - 1e-7)

      loss = -(y * torch.log(y_pred) +(1 - y) * torch.log(1 - y_pred))

      return loss.mean()

    def update(self, loss):

        loss.backward()

        with torch.no_grad():
            self.w -= 0.001 * self.w.grad
            self.b -= 0.001 * self.b.grad

            self.w.grad.zero_()
            self.b.grad.zero_()

In [ ]:
x=torch.randint(size=(10,7), low=20, high=70, dtype=torch.float64)
x

tensor([[37., 59., 44., 57., 23., 59., 33.],
        [22., 44., 49., 58., 54., 40., 60.],
        [32., 54., 39., 57., 57., 28., 31.],
        [61., 21., 25., 57., 68., 27., 28.],
        [34., 46., 64., 33., 52., 26., 40.],
        [39., 29., 60., 28., 34., 49., 65.],
        [36., 69., 55., 69., 67., 50., 58.],
        [22., 63., 57., 22., 49., 21., 35.],
        [46., 40., 45., 56., 26., 34., 58.],
        [35., 69., 29., 36., 59., 45., 20.]], dtype=torch.float64)

In [ ]:
y=torch.randint(size=(10,),low=0,high=2, dtype=torch.float64)
y

tensor([1., 1., 1., 1., 0., 1., 0., 1., 1., 1.], dtype=torch.float64)

In [ ]:
model=SimpleNN(x,y)

In [ ]:
model.x

tensor([[37., 59., 44., 57., 23., 59., 33.],
        [22., 44., 49., 58., 54., 40., 60.],
        [32., 54., 39., 57., 57., 28., 31.],
        [61., 21., 25., 57., 68., 27., 28.],
        [34., 46., 64., 33., 52., 26., 40.],
        [39., 29., 60., 28., 34., 49., 65.],
        [36., 69., 55., 69., 67., 50., 58.],
        [22., 63., 57., 22., 49., 21., 35.],
        [46., 40., 45., 56., 26., 34., 58.],
        [35., 69., 29., 36., 59., 45., 20.]], dtype=torch.float64)

In [ ]:
model.y

tensor([1., 1., 1., 1., 0., 1., 0., 1., 1., 1.], dtype=torch.float64)

In [ ]:
model.w

tensor([[0.0182],
        [0.9563],
        [0.9702],
        [0.8947],
        [0.8241],
        [0.4975],
        [0.1982]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.b

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
y_pred=model.forwardPass()
y_pred

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [ ]:
loss=model.calculate_loss(y_pred)
loss

tensor(3.2236, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [ ]:
model.update(loss)

In [ ]:
model.w

tensor([[0.0182],
        [0.9563],
        [0.9702],
        [0.8947],
        [0.8241],
        [0.4975],
        [0.1982]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.b

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
model = SimpleNN(x, y)

for epoch in range(10):

    y_pred = model.forwardPass()

    loss = model.calculate_loss(y_pred)

    loss.backward()

    with torch.no_grad():
        model.w -= 0.001 * model.w.grad
        model.b -= 0.001 * model.b.grad

    model.w.grad.zero_()
    model.b.grad.zero_()
    print(loss.item())

TypeError: SimpleNN.calculate_loss() missing 1 required positional argument: 'y_pred'